[project]
name = "metadata-generator"
version = "0.2.1"
description = "Kura projects metadata generator"
readme = "README.md"
authors = [
    { name = "eclipse.kura", email = "kura-dev@eclipse.org" }
]
requires-python = ">=3.9"
dependencies = [
    "jproperties>=2.1.2",
]

[project.scripts]
kura-gen = "metadata_generator:main"

[project.urls]
"Homepage" = "https://github.com/eclipse-kura/metadata-generator"
"Bug Tracker" = "https://github.com/eclipse-kura/metadata-generator/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
